# Generated by Django 3.2.5 on 2021-07-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210727_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='borrower',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
